#!/usr/bin/expect -f

# remote linux file system example (for root)

log_user 0

spawn sshfs -o password_stdin -o "StrictHostKeyChecking=no" -p 22 root@111.222.333.444:/ /mnt/rbfl
send "your_root_password\r"

expect timeout {
    log_user 1
    puts "fail"
    exit 1
}

exit 0
